version: '3.8'

services:
  drogon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./drogon_config:/usr/local/drogon/config
    command: "/usr/local/drogon/bin/drogon -c /usr/local/drogon/config/config.json"